apiVersion: v1
kind: Service
metadata:
  name: server-service
# spec:
#     type: LoadBalancer
#     ports:
#         - port: 80
#     selector:
#         app: server
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  selector:
    app: server